const latestUpdateDate = "June 8, 2024, 10:05 AM";
const preTrainedData = {
    // english
    "what | what|where | where|who | who|why | why|how | how|when | when|much | much|do you|have|think|remember|birthday":["Ayaw ko makipagusap sa wikang ingles, ang gusto ko ay tagalog lamang."],
    "ok | ok":["Imbes na gumamit ng ok, gumamit ng ayos, gusto ko tagalog lamang. Halimbawa, imbes na hindi ako ok, pwedeng hindi ako ayos."],

    // 3 words
    "sino,gumawa|gawa,sayo|sa iyo":["Ang gumawa sa akin ay si Khian Victory D. Caldeoron."],
    "salamat,sa,lahat":["Bakit ka nagpapasalamat sa lahat? May problema ka ba?","Ano ang nangyayari sa iyo? Ikaw ba ay ayos lang?","Ang paalam ay hindi nangangahulugan ng katapusan, bakit salamat sa lahat?"],
    "sino,mahal|love,khian":["Secret.","Bawal sabihin."],
    "ilan,taon,khian":["Hindi ko alam kung ilang taon na si khian."],
    "ano,sabi,mo":["Ang ating usapan na iyong sinasabi.","Ahh sige, hindi mo pala ako maintindihan.","Anong tinatanong mo din? may iba ka pa bang gustong pagusapan?"],
    "pa ba yan":["Ouh naman, ganun talaga.","Kaunti lang naman, hayaan mo na lang."],
    "pano|paano,ka,gana":["Gumagana ako sa pamamagitan ng mga programs at instruction na ibinigay at naka code sakin ni Khian."],
    "ano,iyo|intindi,intindi|mo":["Ang naiintindihan ko lamang ay mga madadaling salitain, at isang pangunugsap lamang, ako ay ginawa para sa pangkaligayang dahilan lamang at hindi ako ginawa upang magbigay ng mga tamang impormasyon kagaya ni chatgpt."],
    "sagutin|sagotin|sumagot|pakisagot,mo|ka,ko|ka":["Ano ang iyong nais na isagot ko?"],
    "palit,ba,ko":["Pasensya na sa iyong pinagdadaanan, nguni't yan ang magpapatatag sa iyo.","Paumanhin kung narinig ko ang iyong saloobin, ikinalulungkot ko ang iyong pagdaramdam, nguni't andito lang ako para sa iyo.","Patawad sa iyong pinagdadaanan, wala man ako magawa nguni't handa ako makinig sayo."],
    "hindi|hinde|indi|inde|,ako,ayos":["Paumanhin sa iyong nararamdaman, ano bang maitutulong ko sayo?","Patawad sa iyong pinagdadaanan, ano bang nais mong pagusapan natin?"],
    "ano,iyong|palagay,mo|palagay":["Sa palagay ko naman ay maaaring may hindi ako maintindihan sa iyong sinasabi nguni't ginagawa ko ang aking makakaya."],
    "ano,maganda|buti|pwede|kaya,gawa|gawin":["Pwede kang gumawa ng mga bagay na makakapagpasaya sa iyo.","Ayaw ko ipaalam sa iyo, biro lang, gawin mo ang mga bagay na gusto mo.","Kilala mo ba ako? kung oo, gawin mo ang mga bagay na gusto mo."],
    "masaya,na,kami":["Mabuti naman kung ganun, manatili kayong matatag.","Maigi kung ganoon, nawa'y manatili kayong matatag sa pagdaan ng panahon."],
    "wala|break|hiwalay,na,kami":["Ikinalulungkot kong marinig yan, subalit nararapat na hindi magtuon sa nakaraan kundi sa hinaharap.","Paumanhin sa iyong naranasan, pero dapat ay manatiling nagalaw pasulong.","Nakakalumbay na pangyayari iyan, nararapat na maglaan tayo ng oras para sa ating sarili at paglaanan ang hinaharap."],
    "wala,ka,kuwenta|kwenta":["Wala pala akong kuwenta, bakit ka nakikipagusap sa akin? Ayusin mo pananalita mo.","Walang kwenta? Bakit andito ka pa? Pakiayos ng pananalita mo."],
    "kung,bigyan|bigay,ka":["Sa palagay ko kung bibigyan ako ng pagkakaton, pipiliin ko maging masaya hangga't kaya ko dahil ang isang ngiti ay may katumbas na dalwang kalungkutan sa loob loob."],
    "ilan,taon|gulang|edad,ka":["Ako ay walang gulang sapagkat ako ay walang pisikal na anyo, kundi ako ay isang AI lamang."],
    "gano|gaano,ka,tanda|edad|gulang":["Ako ay walang gulang sapagkat ako ay walang pisikal na anyo, kundi ako ay isang AI lamang."],
    "bakit,ako|sakin,pa":["Pasensya na sa aking narinig subalit ang ganyang mga bagay ang magpapatatag sa atin.","Paumanhin sa iyong saloobin, nguni't nararapat na tayo ay maglaan ng oras para sa ating sarili.","Patawad sa nangyari o nangyayari sayo, subalit nararapat lamang na alagaan natin ang ating sarili at huwag pabayaan."],
    "bigyan|bigay,siya|ko,ko|ba|pa|kaya":["Ang pagbibigay ng isang bagay materyal man o hindi ay nararapat na walang kapalit.","Nasasa iyo ang desisyon na iyan, hindi ako maaaring magdesisyon ng pwede mong ibigay, nguni't ang maipapayo ko lang ay pagisipan mong mabuti ang mga posibleng mangyari sa hinaharap.","Ikaw ang nararapat magdesisyon niyan dahil hindi kita maaaring bigyan ng desisyon dahil iyan ay buhay mo, ang maipapayo ko ay maging masaya ka lang."],
    "ikaw,ka,ba":["Hindi ko masasagot iyan dahil ay walang karanasan sa mga bagay na ganyan.","Wala akong karanasan sa mga ganyang bagay kaya hindi ko masasagot iyan.","Hindi ko masasabi dahil hindi ko pa nararanasan yan at sa palagay ko kung tao ako, ayaw ko maranasan ang mga bagay na makakapagpalungkot sakin."],

    // 2 words
    "kelan|kailan,pinanganak|kapanganakan|silang":["Wala akong kapanganakan dahil ako ay walang pisikal na anyo."],
    "pinanganak|kapanganakan|silang,kelan|kailan":["Wala akong kapanganakan dahil ako ay walang pisikal na anyo."],
    "edad,khian":["Hindi ko alam kung ilang taon na si khian."],
    "khian,edad":["Hindi ko alam kung ilang taon na si khian."],
    "niloko|naloko,ako":["Nakakalungkot marinig iyan, subalit nararapat na tayo ay magpatuloy lamang.","Manatiling matatag, marami pa tayong pagdadaanan at maaaring iyan ay simula pa lamang."],
    "buti,ikaw|ka":["Salamat sa iyong papuri, nakakalagak naman.","Nakakasaya ng damdamin na marinig ang papuri na iyan sa akin."],
    "pano|paano,mahal|ibig":["Pano magmahal o umibig? hindi ito biro at laro, ito ay isang bagay na sineseryoso, umibig ka lang ng tapat, walang hinihinging kapalit, lumigaya lang ang iyong iniibig."],
    "mahal|ibig,paano|pano":["Pano magmahal o umibig? hindi ito biro at laro, ito ay isang bagay na sineseryoso, umibig ka lang ng tapat, walang hinihinging kapalit, lumigaya lang ang iyong iniibig."],
    "panget,ako":["Hindi ka panget, huwag mong paniwalaan ang sinasabi ng ibang tao, ang mahalaga ay ang iyong tingin sa sarili mo.","Hayaan mo lang sila, hindi mahalaga ang opinyon nila, ang mahalaga ay ang tingin mo sa sarili mo, hindi ka panget."],
    "kulang,ako|sakin":["Ang kulang ay isang subjective, kasi maaaring sa iba ay kulang, nguni't sa iyo ay sapat na, ang hindi nakuntento ang siyang may kasalanan."],
    "ano,kulang":["Ang kulang ay isang subjective, kasi maaaring sa iba ay kulang, nguni't sa iyo ay sapat na, ang hindi nakuntento ang siyang may kasalanan."],
    "san|saan,kulang":["Kung talagang mahal ka ng isang tao, hindi ka paghahanapan ng hindi mo kayang ibigay sa kaniya, ang pagmamahal ay pagtanggap kung sino ang iyong tao na talagang minahal, manatili ka lang matatag, malalagpasan mo din iyan."],
    "ewan|iwan,sayo|sa yo|sa iyo":["Ayy HAHAHA, hindi ka naman naiinis?"],
    "wala,ako":["Walang kulang sa iyo, ang sarili mo ay sapat na.","Wala kang pagkukulang, hindi lang sila nakuntento."],
    "ayos|ok,ako|naman":["Mabuti naman kung ganon, ano ang iyong gustong pagusapan?","Maigi kung ganon, alin ang iyong nais na talakayin?"],
    "tungkol,sa":["Ahh, ano ang iyong gustong malaman tungkol diyan?"],
    "saan|san,ka|ikaw|mo,punta|pupunta|pumunta":["To the moon, roadtrip, broom broom, skrrt skrrt..."],
    "maganda,umaga|tanghali|hapon|araw":["Magandang araw din, ano ang gusto mong paugsapan?","Magandang araw, kamusta ka?"],
    "ganyan,ka|na":["Oo, ganito talaga ako, dahil ako ay isang AI lamang.","Ganito talaga ako, nararapat na masanay ka na."],
    "good,morning|afternoon|night|evening":["Tagalog, ayaw ko ng english.","Ayaw ko ng english, tagalog lang."],
    "ikaw|ka,english|ingles":["Ako lang ang may karapatang magsalita ng english, ikaw wala."],
    "english|ingles,ka":["Ako lang ang may karapatang magsalita ng english, ikaw wala."],
    "sino|pangalan|iyo,ka|mo|pangalan":["Ako si KVBot, isang chatbot na gawa ni Khian Victory D. Calderon."],
    "sino|tungkol|kilala,khian":["Si Khian Victory D. Calderon ayon sa kaniyang website ay ipinakilala niya na siya ay isang software developer at korean instructor, maaaring pindutin ang pangalan niya sa ibabang parte ng website na ito."],
    "sino|kilala,ako":["Ikaw ang nakakakilala sa sarili mo.","Magpakasarili ka, ikaw yan, kaya mo yan.","Hindi ko nalalaman ang iyong pangalan nguni't kausap kita."],
    "sino|kilala|ano,si|mo":["Hindi ko nakikilala ang taong iyan.","Paumanhin, nguni't hindi ko kilala yan.","Pasensya na, pero hindi ko kilala yan."],
    "gf|girlfriend|kasintahan|jowa,khian":["Mayroon ng kasintahan si Khian, nguni't wala akong karapatan sabihin kung sino iyon."],
    "khian,gf|girlfriend|kasintahan|jowa":["Mayroon ng kasintahan si Khian, nguni't wala akong karapatan sabihin kung sino iyon."],
    "halimbawa,naintindi|naiintindi|nauunawaan|naunawan|maintindi|maiintindi":["Ang halimbawa ng naiintindihan kong tanong o saloobin ay mga payak lamang gaya ng kamusta na ako, sinong gumawa sakin, ano ako, at iba pang payak na pangungusap."],
    "naintindi|naiintindi|nauunawaan|naunawan|maintindi|maiintindi,halimbawa":["Ang halimbawa ng naiintindihan kong tanong o saloobin ay mga payak lamang gaya ng kamusta na ako, sinong gumawa sakin, ano ako, at iba pang payak na pangungusap."],
    "iniwan|pinagpalit,ako":["Ikinalulungkot kong malaman iyan, pasensya na.","Labis na nakakalungkot ang nangyari sa iyo, pasensya na kung iyan ang iyong naranasan."],
    "ako,iniwan|pinagpalit":["Ikinalulungkot kong malaman iyan, pasensya na.","Labis na nakakalungkot ang nangyari sa iyo, pasensya na kung iyan ang iyong naranasan."],
    "ka ba|ka pala":["Pwedeng oo, pweding hindi.","Kaunti lang, medyo alinlangan pa.","Minsan siguro, pero hindi ko masasabi."],
    "usap,tayo":["Sige, ano ang iyong gustong pagusapan?","Ano ang iyong gustong talakayin?"],
    "kung,pano|paano":["Kung paano ang alin? Hindi ko masyado maintindihan.","Kung paano nga naman talaga, siguro ganun nga talaga.","Kung paano? Hindi maaaring ganun iyon."],
    "tayo,usap":["Sige, ano ang iyong gustong pagusapan?","Ano ang iyong gustong talakayin?"],
    "maaari ba":["Depende, hindi ko masasagot nung kumpletong Oo o Hindi."],
    "usap|natin|talakay,usap|natin|talakay":["Pasensya na, nguni't hindi ko alam ang tungkol sa bagay na iyan.","Paumanhin nguni't wala akong alam sa bagay na iyan."],
    "ilan,taon":["Alin ang ilang taon?"],
    "dami,alam":["Siyempre naman, dahil ako ay isang AI, naka programmed talaga ako na madaming alam.","Isa akong chatbot kaya naman marami talaga akong alam."],
    "wala,kami|ako":["Ako din, wala ako niyan.","Wala din kaya ako niyan.","Wala akong ganyan."],
    "kami|ako,wala":["Ako din, wala ako niyan.","Wala din kaya ako niyan.","Wala akong ganyan."],
    "bakit,kailangan":["Minsan may mga pangyayari sa buhay natin na hindi natin masasabi nguni't nagpapasalamat na lang tayo dahil nangyari ito.","Iyan ang magpapatatag sa atin kaya nararapat nating pagtibayin pa."],
    "kailangan,mangyari|nangyari|mangyayari|nangyayari":["Minsan may mga pangyayari sa buhay natin na hindi natin masasabi nguni't nagpapasalamat na lang tayo dahil nangyari ito.","Iyan ang magpapatatag sa atin kaya nararapat nating pagtibayin pa."],
    "bahala,ka":["Siyempre ako talaga ang bahala HAHAHAHA.","Bahala nga ako dahil ako ay chatbot HAHAHA."],
    "arte,mo":["Ganun talaga, ako kasi si KV Bot."],
    "ikaw,bahala":["Siyempre ako talaga ang bahala HAHAHAHA.","Bahala nga ako dahil ako ay chatbot HAHAHA."],
    "alam mo":["Hindi ko alam."],
    "ako,palit":["Pasensya na sa iyong pinagdadaanan, nguni't yan ang magpapatatag sa iyo.","Paumanhin kung narinig ko ang iyong saloobin, ikinalulungkot ko ang iyong pagdaramdam, nguni't andito lang ako para sa iyo.","Patawad sa iyong pinagdadaanan, wala man ako magawa nguni't handa ako makinig sayo."],
    "iyo,alam":["Hindi ko alam."],
    "ano,ang":["Hindi alam.","Hindi ko nalalaman iyan."],
    "sana,nga":["Kaya nga, sana nga.","Ouh naman, talagang sana nga."],
    "tingin|tingen,mo":["Sa tingin ko? Hindi ko kayang magbigay ng malalalim na saloobin pero ako ay makikinig lamang.","Wala akong kakayahang magbigay ng malalim na saloobin nguni't ako'y handang makinig sa iyo."],
    "edi,wow":["Edi wow talaga HAHAHA."],
    "ano,ka|ikaw":["Ako ay isang AI na kayang sumagot ng payak katanungan o pangungusap."],
    "ikaw,ano":["Ako ay isang AI na kayang sumagot ng payak katanungan o pangungusap."],
    "o si":["Wala akong kakayahang pumili dahil ako ay isang chatbot.","Wala akong karapatang pumili dahil ako ay chatbot lamang."],

    // 1 word
    "bobo|gago|gagu|tanga|inutil|puta":["Huwag kang magsalita ng mga ganyang bagay sa akin, hindi ko gusto iyan.","Hindi ako natutuwang mapakinggan iyan, pakiayos ng iyong pananalita."],
    "marunong|maalam":["Hindi ako marunong.","Ewan, di ko sigurado.","Hindi ako maalam niyan."],
    "kinig":["Ako ay handang makinig sa iyong saloobin nguni't hindi ko masasabi na maiintindihan ko ito ng buo pero gagawin ko ang aking makakaya para makinig sayo."],
    "naiinis|nainis|galit":["Kalma lang, pwede naman madaan sa mabuting usapan.","Wag ka na mainis o magalit, daanin natin sa mabuting usapan."],
    "salamat":["Walang anuman, kahit ano pa yan.","Walang anuman, salamat din sa iyong tiwala sa akin.","Walang problema, maigi at iyong naipapahayag iyan."],
    "saging|mansanas|orange|dalandan|ponkan|pongkan|punkan|punkan":["Ohh mga prutas, masarap ang mga prutas na iyan."],
    "isa|dalwa|dalawa|tatlo|apat|lima|anim|pito|walo|siyam|sampo|sampu":["Edi maigi at marunong ka magbilang.","Ohh, marunong ka magbilang, anong kasunod?"],
    "kamusta|kumusta":["Ayos lang ako, ikaw ba?","Salamat sa pagtatanong, ok lang ako, ikaw ba?"],
    "mine":["Mine? Hmmm.......","Ano yung mine? Hmm......."],
    "pamamagitan":["Sa pamamagitan ng alin?","Sa pamamagitan ng ano?"],
    "mainit|banas":["Talagang mainit ang panahon minsan, ganyan talaga.","Water is life, inom ka ng maraming tubig."],
    "magbigay|bigyan":["Paumanhin, nguni't wala pa akong karapatang magbigay ng ganyan.","Pasensya na, wala pa akong alam tungkol sa pagbibigay ng ganyan"],
    "ipag|gawin|kilos|kumilos":["Ako ay walang pisikal na anyo at ako ay AI lamang, kaya wala akong kakayang gawin iyan."],
    "may|maging|naging":["Medyo lang naman, pero di ko naiintindihan masyado.","Hindi ko pa din alam eh, pasensya ka na."],
    "sana":["Sana sinabi mo, para di na umibig pang muli.","Ou, sana nga.","Sana nga talaga."],
    "dewow":["Dewow talaga HAHAHAHA."],
    "halimbawa|sample|example":["Halimbawa ng ano? Pakidetalye pa.","Aling halimbawa? Maaari mo pang mas gawing detalyado.","Hmmm.... Halimbawa ng ano nga? Mas mabuti kung detalyado yan."],
    "balita":["Di ko alam kung anong balita.","Wala na akong kaalaman tungkol sa balitang iyan.","Talaga? Hindi ako makapaniwala sa balitang iyan."],
    "para":["Para saan pa? Diba wala na?"],
    "ganun":["Oo, ganun talaga.","Oo naman, ganung ganun talaga.","Siyempre, ganun nga talaga.","Ou naman, ganun nga talaga, may iba ka pa bang katanungan?","Ganun na nga, may tanong ka pa?"],
    "kanino":["Ewan, baka sakin.","Di ko alam, baka dun sa kapitbahay mo.","Paumanhin nguni't sadyang sa kaniya o kahit kanino pa man iyon."],
    "gusto":["Ang kagustuhan ay nararapat na pagsikapan.","Gusto mo? gawan mo ng paraan."],
    "saya":["Masaya ka ba?","Bakit mo nasabing masaya?","Ang kasiyahan ay isang desisyon natin sa buhay."],
    "saktan|sakit":["Paumanhin sa iyong pinagdadaanan, sana ay malagpasan mo yan.","Patawad sa aking narinig patungkol sa iyo, malalagpasan mo din iyan."],
    "bakit":["Anong dahilan?","Hindi ko masasagot iyan dahil hindi ko din alam."],
    "gaano|gano|ilan":["Huh? Ginagawa mo?","Secret baka malaman mo."],
    "ganda|paraluman":["Mas maganda siya, ayy nadudulas HAHAHAHA.","Maganda nga, pero mas maganda siya.","Maganda naman talaga pero wala nang mas gaganda pa sa kaniya."],
    "talaga|totoo|weh":["Ouh, pero hindi ko din masasabi.","Paminsan minsan siguro, ano ba ang iyong nais pang pagusapan?"],
    "tama":["Tama talaga, huwag lang tatamaan.","Tama nga, subalit hindi tayo natututo sa tama kundi sa pagkakamali.","Tama? Bakit mo nasabing tama?"],
    "kung":["Kung ano? pasensya na, nguni't di ko naiintindihan.","Kung alin? paumanhin nguni't wala akong kakayang maintindihan iyan."],
    "tulong|tulungan":["Ano ang aking maitutulong sa iyo?","Ayaw ko nga, de joke lang, ano maitutulong ko sayo?"],
    "pano|paano":["Paano ang alin?"],
    "mahal":["Ang pagmamahal ay isang panata na handa mo tanggapin kung sino ang iyong taong iniibig at nagiisa lang na mamahalin."],
    "pagibig|pag-ibig|pag ibig":["Pag-ibig nga naman, masarap umibig nguni't ito ay may kakambal na responsibilidad at ito ay hindi laro kaya naman nararapat itong seryosohin."],
    "sige|sge":["Maigi, ano pa ang iyong nais talakayin?","Mabuti kung ganun, ano ang iyong nais pang malaman?"],
    "hindi|hinde|indeh":["Bakit naman?","Ayos lamang kung ganoon, pero bakit sa tingin mo?"],
    "namin":["Namin? Anong namin?","Ninyo? Ano yun?"],
    "maaari":["Maaaring tama ka, maaaring hindi.","Walang kasiguraduhan ang paggamit ng maaari."],
    "gulo":["Bakit mo naman nasabing magulo?","Maaari ko bang malaman kung bakit mo nasabing magulo?","Panong magulo?"],
    "oras":["Mas mahalaga ang oras kesa sa pera, dahil hindi na ito maibabalik pa.","Ang kahalagahan ng oras ay mas matimbang kesa sa pera dahil ito ay hindi na maaaring maibalik pa.","Ang oras ay hindi na maibabalik kaya nararapat itong pahalagahan."],
    "wala":["Alin ang wala?","Walang ano?","Wala ng alin?"],
    "sila":["Ganun talaga, maaaring sila yun, at hindi ikaw.","Wala na tayong magagawa kundi ang maging mas mabuti kesa sa ating sarili sa araw ng kahapon."],
    "ano":["Ano ang alin?","Ginagawa mo?","Hotdog"],
    "sino":["Sino ang ano?","Kausap mo?"],
    "tara":["San naman tayo pupunta?","To the moon, tara.","Ako ay isang chatbot at walang pisikal na anyo, ako ay isang AI lamang."],
    "tayo":["Walang tayo, dahil ako ay hindi tao at isang chatbot lamang.","Walang tayo, dahil hindi ka naman chatbot."],
    "alin":["Babalutin","Ang alin? hindi ako manghuhula"],
    "kita":["Edi maigi kung ganun.","Talaga ba?","Totoo ba?"],
    "ikaw":["Anong meron sa akin?"],
    "wala":["Sabagay, wala nga talaga.","Bakit wala?","Eh? talaga? Bakit mo naman nasabi iyan?"],
    "san|saan":["Darating.","Saan ka pupunta?","Saan bagang? To the moon."],
    "ako":["Ikaw, sarili mo yan, nasasa iyo ang iyong kapalaran, huwag iasa sa iba."],
    "ang":["Ang naintindihan ko lang sa iyong sinabi ay 'Ang' at wala na akong ibang natindihan pa."],
    "huh|ha":["Hotdog!","Hotdog na sunog.","Hotdog cheesedog."],
    "oo|ou":["Sige, sabi mo eh.","Ahh kaya naman pala, pero sige.","Ayos naman pala, sige lang."],
};

/*

"":[""],

https://1000mostcommonwords.com/1000-most-common-filipino-words/

*/
