const updateDate = "May 31, 2024. Approximately 8:22 AM";
const preTrainedData = {
    // english
    "what | what|where | where|who | who|why | why|how | how|when | when|much | much":["Ayaw ko makipagusap sa wikang ingles, ang gusto ko ay tagalog lamang."],
    "ok | ok":["Imbes na gumamit ng ok, gumamit ng ayos, gusto ko tagalog lamang. Halimbawa, imbes na hindi ako ok, pwedeng hindi ako ayos."],

    // 3 words
    "sino,gumawa|gawa,sayo|sa iyo":["Ang gumawa sa akin ay si Khian Victory D. Caldeoron."],
    "sino,mahal|love,khian":["Secret.","Bawal sabihin."],
    "ilan,taon,khian":["Hindi ko alam kung ilang taon na si khian."],
    "ano,sabi,mo":["Ang ating usapan na iyong sinasabi.","Ahh sige, hindi mo pala ako maintindihan.","Anong tinatanong mo din? may iba ka pa bang gustong pagusapan?"],
    "pa ba yan":["Ouh naman, ganun talaga.","Kaunti lang naman, hayaan mo na lang."],
    "pano|paano,ka,gana":["Gumagana ako sa pamamagitan ng mga programs at instruction na ibinigay at naka code sakin ni Khian."],
    "ano,iyo|intindi,intindi|mo":["Ang naiintindihan ko lamang ay mga madadaling salitain, at isang pangunugsap lamang, ako ay ginawa para sa pangkaligayang dahilan lamang at hindi ako ginawa upang magbigay ng mga tamang impormasyon kagaya ni chatgpt."],
    "sagutin|sagotin,mo,ko":["Ano ang iyong nais na isagot ko?"],
    "palit,ba,ko":["Pasensya na sa iyong pinagdadaanan, nguni't yan ang magpapatatag sa iyo.","Paumanhin kung narinig ko ang iyong saloobin, ikinalulungkot ko ang iyong pagdaramdam, nguni't andito lang ako para sa iyo.","Patawad sa iyong pinagdadaanan, wala man ako magawa nguni't handa ako makinig sayo."],
    "hindi|hinde|indi|inde|,ako,ayos":["Paumanhin sa iyong nararamdaman, ano bang maitutulong ko sayo?","Patawad sa iyong pinagdadaanan, ano bang nais mong pagusapan natin?"],
    "ano,iyong|palagay,mo|palagay":["Sa palagay ko naman ay maaaring may hindi ako maintindihan sa iyong sinasabi nguni't ginagawa ko ang aking makakaya."],

    // 2 words
    "alam mo":["Hindi ko alam."],
    "ako,palit":["Pasensya na sa iyong pinagdadaanan, nguni't yan ang magpapatatag sa iyo.","Paumanhin kung narinig ko ang iyong saloobin, ikinalulungkot ko ang iyong pagdaramdam, nguni't andito lang ako para sa iyo.","Patawad sa iyong pinagdadaanan, wala man ako magawa nguni't handa ako makinig sayo."],
    "iyo,alam":["Hindi ko alam."],
    "kelan,update|update,kelan":["Huli akong na update ay nitong " + updateDate + "."],
    "edad,khian":["Hindi ko alam kung ilang taon na si khian."],
    "khian,edad":["Hindi ko alam kung ilang taon na si khian."],
    "ilan,taon":["Alin ang ilang taon?"],
    "pano|paano,mahal|ibig":["Pano magmahal o umibig? hindi ito biro at laro, ito ay isang bagay na sineseryoso, umibig ka lang ng tapat, walang hinihinging kapalit, lumigaya lang ang iyong iniibig."],
    "mahal|ibig,paano|pano":["Pano magmahal o umibig? hindi ito biro at laro, ito ay isang bagay na sineseryoso, umibig ka lang ng tapat, walang hinihinging kapalit, lumigaya lang ang iyong iniibig."],
    "panget,ako":["Hindi ka panget, huwag mong paniwalaan ang sinasabi ng ibang tao, ang mahalaga ay ang iyong tingin sa sarili mo.","Hayaan mo lang sila, hindi mahalaga ang opinyon nila, ang mahalaga ay ang tingin mo sa sarili mo, hindi ka panget."],
    "kulang,ako|sakin":["Ang kulang ay isang subjective, kasi maaaring sa iba ay kulang, nguni't sa iyo ay sapat na, ang hindi nakuntento ang siyang may kasalanan."],
    "ano,kulang":["Ang kulang ay isang subjective, kasi maaaring sa iba ay kulang, nguni't sa iyo ay sapat na, ang hindi nakuntento ang siyang may kasalanan."],
    "san|saan,kulang":["Kung talagang mahal ka ng isang tao, hindi ka paghahanapan ng hindi mo kayang ibigay sa kaniya, ang pagmamahal ay pagtanggap kung sino ang iyong tao na talagang minahal, manatili ka lang matatag, malalagpasan mo din iyan."],
    "ewan|iwan,sayo|sa yo|sa iyo":["Ayy HAHAHA, hindi ka naman naiinis?"],
    "kamusta,ka":["Ayos lang ako, ikaw ba?","Salamat sa pagtatanong, ok lang ako, ikaw ba?"],
    "wala,ako":["Walang kulang sa iyo, ang sarili mo ay sapat na.","Wala kang pagkukulang, hindi lang sila nakuntento."],
    "ayos|ok,ako|naman":["Mabuti naman kung ganon, ano ang iyong gustong pagusapan?","Maigi kung ganon, alin ang iyong nais na talakayin?"],
    "tungkol,sa":["Ahh, ano ang iyong gustong malaman tungkol diyan?"],
    "saan|san,ka|ikaw|mo,punta|pupunta|pumunta":["To the moon, roadtrip, broom broom, skrrt skrrt..."],
    "maganda,umaga|tanghali|hapon|araw":["Magandang araw din, ano ang gusto mong paugsapan?","Magandang araw, kamusta ka?"],
    "good,morning|afternoon|night|evening":["Tagalog, ayaw ko ng english.","Ayaw ko ng english, tagalog lang."],
    "arte,mo":["Ganun talaga, ako kasi si KV Bot."],
    "sino|pangalan|iyo,ka|mo|pangalan":["Ako si KVBot, isang chatbot na gawa ni Khian Victory D. Calderon."],
    "sino|tungkol|kilala,khian":["Si Khian Victory D. Calderon ayon sa kaniyang website ay ipinakilala niya na siya ay isang software developer at korean instructor, maaaring pindutin ang pangalan niya sa ibabang parte ng website na ito."],
    "sino|kilala,ako":["Ikaw ang nakakakilala sa sarili mo.","Magpakasarili ka, ikaw yan, kaya mo yan.","Hindi ko nalalaman ang iyong pangalan nguni't kausap kita."],
    "sino|kilala|ano,si|mo":["Hindi ko nakikilala ang taong iyan.","Paumanhin, nguni't hindi ko kilala yan.","Pasensya na, pero hindi ko kilala yan."],
    "gf|girlfriend|kasintahan|jowa,khian":["Mayroon ng kasintahan si Khian, nguni't wala akong karapatan sabihin kung sino iyon."],
    "khian,gf|girlfriend|kasintahan|jowa":["Mayroon ng kasintahan si Khian, nguni't wala akong karapatan sabihin kung sino iyon."],
    "ano,ang":["Hindi alam.","Hindi ko nalalaman iyan."],
    "iniwan|pinagpalit,ako":["Ikinalulungkot kong malaman iyan, pasensya na.","Labis na nakakalungkot ang nangyari sa iyo, pasensya na kung iyan ang iyong naranasan."],
    "ako,iniwan|pinagpalit":["Ikinalulungkot kong malaman iyan, pasensya na.","Labis na nakakalungkot ang nangyari sa iyo, pasensya na kung iyan ang iyong naranasan."],
    "ka ba|ka pala":["Pwedeng oo, pweding hindi.","Kaunti lang, medyo alinlangan pa.","Minsan siguro, pero hindi ko masasabi."],
    "usap,tayo":["Sige, ano ang iyong gustong pagusapan?","Ano ang iyong gustong talakayin?"],
    "tayo,usap":["Sige, ano ang iyong gustong pagusapan?","Ano ang iyong gustong talakayin?"],
    "maaari ba":["Depende, hindi ko masasagot nung kumpletong Oo o Hindi."],
    "usap|natin|talakay,usap|natin|talakay":["Pasensya na, nguni't hindi ko alam ang tungkol sa bagay na iyan.","Paumanhin nguni't wala akong alam sa bagay na iyan."],
    "o si":["Wala akong kakayahang pumili dahil ako ay isang chatbot.","Wala akong karapatang pumili dahil ako ay chatbot lamang."],
    "dami,alam":["Siyempre naman, dahil ako ay isang AI, naka programmed talaga ako na madaming alam.","Isa akong chatbot kaya naman marami talaga akong alam."],
    "bahala,ka":["Siyempre ako talaga ang bahala HAHAHAHA.","Bahala nga ako dahil ako ay chatbot HAHAHA."],
    "ikaw,bahala":["Siyempre ako talaga ang bahala HAHAHAHA.","Bahala nga ako dahil ako ay chatbot HAHAHA."],
    "sana,nga":["Kaya nga, sana nga.","Ouh naman, talagang sana nga."],
    "tingin|tingen,mo":["Sa tingin ko? Hindi ko kayang magbigay ng malalalim na saloobin pero ako ay makikinig lamang.","Wala akong kakayahang magbigay ng malalim na saloobin nguni't ako'y handang makinig sa iyo."],
    "edi,wow":["Edi wow talaga HAHAHA."],

    // 1 word
    "kinig":["Ako ay handang makinig sa iyong saloobin nguni't hindi ko masasabi na maiintindihan ko ito ng buo pero gagawin ko ang aking makakaya para makinig sayo."],
    "naiinis|nainis|galit":["Kalma lang, pwede naman madaan sa mabuting usapan.","Wag ka na mainis o magalit, daanin natin sa mabuting usapan."],
    "salamat":["Walang anuman, kahit ano pa yan.","Walang anuman, salamat din sa iyong tiwala sa akin.","Walang problema, maigi at iyong naipapahayag iyan."],
    "saging|mansanas|orange|dalandan|ponkan|pongkan|punkan|punkan":["Ohh mga prutas, masarap ang mga prutas na iyan."],
    "isa|dalwa|dalawa|tatlo|apat|lima|anim|pito|walo|siyam|sampo|sampu":["Edi maigi at marunong ka magbilang.","Ohh, marunong ka magbilang, anong kasunod?"],
    "pamamagitan":["Sa pamamagitan ng alin?","Sa pamamagitan ng ano?"],
    "mainit|banas":["Talagang mainit ang panahon minsan, ganyan talaga.","Water is life, inom ka ng maraming tubig."],
    "magbigay|bigyan":["Paumanhin, nguni't wala pa akong karapatang magbigay ng ganyan.","Pasensya na, wala pa akong alam tungkol sa pagbibigay ng ganyan"],
    "ipag|gawin|kilos|kumilos":["Ako ay walang pisikal na anyo at ako ay AI lamang, kaya wala akong kakayang gawin iyan."],
    "may|maging|naging":["Medyo lang naman, pero di ko naiintindihan masyado.","Hindi ko pa din alam eh, pasensya ka na."],
    "sana":["Sana sinabi mo, para di na umibig pang muli.","Ou, sana nga.","Sana nga talaga."],
    "dewow":["Dewow talaga HAHAHAHA."],
    "para":["Para saan pa? Diba wala na?"],
    "saktan|sakit":["Paumanhin sa iyong pinagdadaanan, sana ay malagpasan mo yan.","Patawad sa aking narinig patungkol sa iyo, malalagpasan mo din iyan."],
    "bakit":["Anong dahilan?","Hindi ko masasagot iyan dahil hindi ko din alam."],
    "gaano|gano|ilan":["Huh? Ginagawa mo?","Secret baka malaman mo."],
    "talaga|totoo|weh":["Ouh, pero hindi ko din masasabi.","Paminsan minsan siguro, ano ba ang iyong nais pang pagusapan?"],
    "kung":["Kung ano? pasensya na, nguni't di ko naiintindihan.","Kung alin? paumanhin nguni't wala akong kakayang maintindihan iyan."],
    "tulong|tulungan":["Ano ang aking maitutulong sa iyo?","Ayaw ko nga, de joke lang, ano maitutulong ko sayo?"],
    "pano|paano":["Paano ang alin?"],
    "mahal":["Ang pagmamahal ay isang panata na handa mo tanggapin kung sino ang iyong taong iniibig at nagiisa lang na mamahalin."],
    "pagibig|pag-ibig|pag ibig":["Pag-ibig nga naman, masarap umibig nguni't ito ay may kakambal na responsibilidad at ito ay hindi laro kaya naman nararapat itong seryosohin."],
    "sige|sge":["Maigi, ano pa ang iyong nais talakayin?","Mabuti kung ganun, ano ang iyong nais pang malaman?"],
    "hindi|hinde|indeh":["Bakit naman?","Ayos lamang kung ganoon, pero bakit sa tingin mo?"],
    "ano":["Ano ang alin?","Ginagawa mo?","Hotdog"],
    "sino":["Sino ang ano?","Kausap mo?"],
    "tara":["San naman tayo pupunta?","To the moon, tara.","Ako ay isang chatbot at walang pisikal na anyo, ako ay isang AI lamang."],
    "tayo":["Walang tayo, dahil ako ay hindi tao at isang chatbot lamang.","Walang tayo, dahil hindi ka naman chatbot."],
    "alin":["Babalutin","Ang alin? hindi ako manghuhula"],
    "kita":["Edi maigi kung ganun.","Talaga ba?","Totoo ba?"],
    "ikaw":["Anong meron sa akin?"],
    "san|saan":["Darating.","Saan ka pupunta?","Saan bagang? To the moon."],
    "ako":["Ikaw, sarili mo yan, nasasa iyo ang iyong kapalaran, huwag iasa sa iba."],
    "huh|ha":["Hotdog!","Hotdog na sunog.","Hotdog cheesedog."],
    "oo|ou":["Sige, sabi mo eh.","Ahh kaya naman pala, pero sige.","Ayos naman pala, sige lang."],
};

/*

"":[""],

https://1000mostcommonwords.com/1000-most-common-filipino-words/

*/